### ISSUE TITLE
[Feature] 외부인 용 랜덤 퀴즈 문제 풀이

### ISSUE THREAD

**Issue by gikhoon** [IT-Cotato/COTATO-BE#247]
## 🪶 추가할 기능 설명
외부인이 예시 문제를 랜덤으로 받고 풀 수 있다

## ✅ 작업 내용

- [x] 랜덤 문제 정보 받기
- [x] 제출하기 -> 결과 확인

## 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/7d54c01d-9cc4-47c8-ad8e-014a83557ffe)
![image](https://github.com/user-attachments/assets/f92bb9be-af42-4d89-80e8-16e299d3d59a)

**Comment by Youthhing** [comment]
엥 한번 활용해보신건가요 ㅋㅋ
